/camera_node:
  ros__parameters:
    camera_info_url: package://rm_startup/config/rm_camera_info.yaml
    exposure_time: 6000
    gain: 16.0

/armor_detector:
  ros__parameters:
    debug: 1

    detect_color: 0 # 0: blue, 1: red
    priority_armors: [100,100,100,10,100,100,100,100,100]
    ignore_armors: [1,2] # ignore armors with specific id

    MIN_BIG_ARMOR_RATIO: 3.2

/armor_tracker:
  ros__parameter:
    debug: 1
    
